const ADD_SELECTED_FEATURE = 'ADD_SELECTED_FEATURE';
const REMOVE_SELECTED_FEATURE = 'REMOVE_SELECTED_FEATURE';
const FETCH_FEATURE_LIST_SUCCESS = 'FETCH_FEATURE_LIST_SUCCESS';
const FETCH_FEATURE_DATA_SUCCESS = 'FETCH_FEATURE_DATA_SUCCESS';
const FETCH_FEATURE_DATA_FAILURE = 'FETCH_FEATURE_DATA_FAILURE';
const FETCH_FEATURE_DATA_FROM_LOCAL_STORAGE_SUCCESS =
    'FETCH_FEATURE_DATA_FROM_LOCAL_STORAGE_SUCCESS';

export {
ADD_SELECTED_FEATURE,
REMOVE_SELECTED_FEATURE,
FETCH_FEATURE_LIST_SUCCESS,
FETCH_FEATURE_DATA_SUCCESS,
FETCH_FEATURE_DATA_FAILURE,
FETCH_FEATURE_DATA_FROM_LOCAL_STORAGE_SUCCESS,
};
